### ISSUE TITLE
feat: 关于文件加密的安全建议

### ISSUE THREAD

**Issue by noisky** [zfile-dev/zfile#222]
目前的加密是识别路径下是否存在加密文件，存在则限制访问，该访问方式会存在潜在安全问题，即二级目录不包含该加密文件的目录都可以直接输入URL访问，或者所有文件都可以直接输入URL进行访问......

是否可以考虑采用本地URL路径匹配的加密方式，在管理后台输入需要加密的目录，在数据库中维护一个目录加密列表，在访问URL的时候进行URL路径匹配，匹配到的加密目录限制访问，这样可解决直接直接访问加密目录下文件的安全性问题。

**Comment by zhaojun1998** [comment]
可以考虑将文件过滤功能，改造为文件夹密码功能

**Comment by jiangjiangflies** [comment]
强烈附议！！！我也提过这样的建议： #79，我看了issue里面，也有很多人提及密码文件的安全隐患： #58 #242，所以这个问题应该算是公共问题了！希望作者重新考虑这个建议！

**Comment by zhaojun1998** [comment]
如果你看过那几个issue中我的回复。也就不会再提这个问题了。


首先，你那文件可以改名字。
如果不知道父文件夹密码，是不可能知道有哪些子文件夹的，所有绕过来直接访问子文件夹也是一个伪命题。
其次程序现在只是记录了成功的密码，以便下次免输入正确的密码。如果改了密码，还是访问不了之前的文件夹的。


之所以不设计读取所有父级文件的密码文件。还是性能考虑。如访问/a/b/c/d/e文件夹时，现在的逻辑只要调用1次api，如果按照你们要的逻辑，就需要调用5次api。访问体验会大幅下降。且onedrive api还有阈值限制。不能一直频繁调用的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月23日(周六) 上午10:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhaojun1998/zfile] feat: 关于文件加密的安全建议 (#222)




 
强烈附议！！！我也提过这样的建议： #79，我看了issue里面，也有很多人提及密码文件的安全隐患： #58 #242，所以这个问题应该算是公共问题了！希望作者重新考虑这个建议！
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiangjiangflies** [comment]
那些issue我都看过了。我觉得您误解我们的意思了。我们的建议是，**完全摒弃使用密码文件**的这个加密做法。
您考虑问题还是基于密码文件考虑的。您可以考虑层主noisky的建议，换个思路，不用密码文件，使用URL路径匹配，这并不需要调用od api，也根本没有进行多次进行文件夹递归验证造成的性能下降问题。
我也在用olaindex，就不是用的密码文件验证，应该就是类似URL路径匹配的做法，个人感觉这种方式非常简单、安全、高效。所以一直也想让zfile汲取优秀经验，变得更加强大！

**Comment by zhaojun1998** [comment]
这个已经在下个版本的计划中了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月23日(周六) 上午10:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhaojun1998/zfile] feat: 关于文件加密的安全建议 (#222)




 
那些issue我都看过了。我觉得您误解我们的意思了。我们的建议是，完全摒弃使用密码文件的这个加密做法。
 您考虑问题还是基于密码文件考虑的。您可以考虑层主noisky的建议，换个思路，不用密码文件，使用URL路径匹配，这并不需要调用od api，也根本没有进行多次进行文件夹递归验证造成的性能下降问题。
 我也在用olaindex，就不是用的密码文件验证，应该就是类似URL路径匹配的做法，个人感觉这种方式非常简单、安全、高效。所以一直也想让zfile汲取优秀经验，变得更加强大！
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiangjiangflies** [comment]
谢谢！！！

**Comment by zhaojun1998** [comment]
@noisky @jiangjiangflies 

非常抱歉这么久才回复，最新版本已经支持递归设置密码功能
