### ISSUE TITLE
请问这个试什么情况

### ISSUE THREAD

**Issue by kyle208** [zfile-dev/zfile#225]
![image](https://user-images.githubusercontent.com/12055155/118469596-6d049300-b738-11eb-9bda-edcf70172287.png)
[zfile.log](https://github.com/zhaojun1998/zfile/files/6492965/zfile.log)

**Comment by zhaojun1998** [comment]
如果是国内机器。用的是国际版的onedrive，可能出现机器到微软api之间网络不稳定等因素。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月17日(周一) 下午5:51
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] 请问这个试什么情况 (#225)




 

 zfile.log

**Comment by kyle208** [comment]
> 如果是国内机器。用的是国际版的onedrive，可能出现机器到微软api之间网络不稳定等因素。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年5月17日(周一) 下午5:51 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [zhaojun1998/zfile] 请问这个试什么情况 (#225) zfile.log — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

是国内的阿里云，一直无法保存成功！

**Comment by zhaojun1998** [comment]
尝试下更换 dns 后重试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月18日(周二) 上午8:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhaojun1998/zfile] 请问这个试什么情况 (#225)




  
如果是国内机器。用的是国际版的onedrive，可能出现机器到微软api之间网络不稳定等因素。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年5月17日(周一) 下午5:51 收件人: @.&gt;; 抄送: @.***&gt;; 主题: [zhaojun1998/zfile] 请问这个试什么情况 (#225) zfile.log — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
是国内的阿里云，一直无法保存成功！

**Comment by kyle208** [comment]
> 尝试下更换 dns 后重试
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年5月18日(周二) 上午8:55 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [zhaojun1998/zfile] 请问这个试什么情况 (#225) 如果是国内机器。用的是国际版的onedrive，可能出现机器到微软api之间网络不稳定等因素。 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年5月17日(周一) 下午5:51 收件人: @.&gt;; 抄送: @.***&gt;; 主题: [zhaojun1998/zfile] 请问这个试什么情况 (#225) zfile.log — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 是国内的阿里云，一直无法保存成功！ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

初始化异常, 错误信息为: I/O error on GET request for "https://graph.microsoft.com/v1.0/me/drive/root/children": graph.microsoft.com; nested exception is java.net.UnknownHostException: graph.microsoft.com
到这一步了，解决不了了。
我ping graph.microsoft.com都ping不通

**Comment by kyle208** [comment]
挂梯子才解决，感谢
