### ISSUE TITLE
是否支持本地目录挂载

### ISSUE THREAD

**Issue by dong4j** [zfile-dev/zfile#256]
比如部署到 192.168.1.1 服务器, 能不能挂载此服务器内某个目录, 然后在页面上显示此目录下的所有文件?

**Comment by zhaojun1998** [comment]
如果部署的机器和文件都在一个服务器，是可以的。类型选择本地存储就好了。

如果不在一台机器，则文件所在服务器需要将文件夹使用 ftp 模式添加，或者自建 minio 来挂载

**Comment by limitationai** [comment]
请教个问题，zfile3.1版本中，我用的安装方法是docker，类型选择我是选择本地储存挂载/目录，其中home里面没有显示我的用户目录，而且我新建的文件夹和文件也没显示出来，请问是出了什么问题？，请求解决方法。

**Comment by zhaojun1998** [comment]
docker需要将你宿主机的文件路径，映射到docker容器内。


docker容器才能访问到。这是docker的隔离机制。请自行查阅docker官方文档。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月13日(周一) 凌晨0:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhaojun1998/zfile] 是否支持本地目录挂载 (#256)




 
请教个问题，zfile3.1版本中，我用的安装方法是docker，类型选择我是选择本地储存挂载/目录，其中home里面没有显示我的用户目录，而且我新建的文件夹和文件也没显示出来，请问是出了什么问题？，请求解决方法。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhaojun1998** [comment]
长期未回复，暂时关闭此问题，有问题再打开。
