### ISSUE TITLE
onedrive点击下载时会跳转让你输入账号密码

### ISSUE THREAD

**Issue by vlssu** [zfile-dev/zfile#265]
## 我的环境
apache2.4
centos8.4
2h4g

## 错误日志
[ZFile 诊断日志 - 2021-08-24 11_31_39.zip](https://github.com/zhaojun1998/zfile/files/7036291/ZFile.-.2021-08-24.11_31_39.zip)

## 期望行为
onedrive世纪联华下载文件

## 当前行为
onedrive世纪联华下载文件时会跳转到登陆页面让你登录，就算登录后也没有下载的意思

**Comment by zhaojun1998** [comment]
你配置加速域名了吧，应该是加速域名配置的有问题。你去掉这个配置先试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月24日(周二) 中午11:35
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] onedrive点击下载时会跳转让你输入账号密码 (#265)




 
我的环境
 
apache2.4
 centos8.4
 2h4g
 
错误日志
 
ZFile 诊断日志 - 2021-08-24 11_31_39.zip
 
期望行为
 
onedrive世纪联华下载文件
 
当前行为
 
onedrive世纪联华下载文件时会跳转到登陆页面让你登录，就算登录后也没有下载的意思
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by vlssu** [comment]
解决了，那你在文档中的反向代理没有太大作用是这样吗

**Comment by zhaojun1998** [comment]
不是啊，肯定是你配置的反向代理有问题，我猜测是这里配置的下载域名有问题 （1 和 2）.

![image](https://user-images.githubusercontent.com/35387985/130560130-0f41052b-b714-40cf-9339-7eb54b0e3a86.png)

**Comment by vlssu** [comment]
下载域名难道不是用OneDrive下载时的那个域名吗，难道说有个通用的域名？

**Comment by zhaojun1998** [comment]
你应该先正常下载你 onedrive 下的文件，然后看看你的账号下载域名是什么，不同账号，下载域名是不一样的，然后填写到这里，其实就是通过 CF 反向代理下载域名。

**Comment by vlssu** [comment]
那我设置是对的啊，就很奇怪

一共有两处需要填写域名，第一个是填写下载域名，那第二处也填写下载域名吗

**Comment by zhaojun1998** [comment]
1 和 2 都要写下载域名

**Comment by vlssu** [comment]
那我设置就是么有问题了，就很奇怪

**Comment by zhaojun1998** [comment]
你可以提供给我你站点地址，你单独建两个驱动器，绑定同一个账号，一个开启域名，一个不开启加速域名，然后截图你的 CF 设置，如果不方便公开在 issue，可发邮件给我：873019219@qq.com

**Comment by zhaojun1998** [comment]
@vlssu  经排查这是个 BUG，感谢反馈，下版本会修复

**Comment by zhaojun1998** [comment]
3.2 版本已解决此问题
