### ISSUE TITLE
docker安装的如何配置物理机硬盘为驱动器？只能配置镜像内路径

### ISSUE THREAD

**Issue by DingChang90** [zfile-dev/zfile#269]
![1630849271(1)](https://user-images.githubusercontent.com/71495804/132128972-c1eef130-bec1-474a-8eac-01c46cfce008.png)
添加物理机挂载的移动硬盘，就提示如图所示。

![1630849331(1)](https://user-images.githubusercontent.com/71495804/132129016-15331b8d-a28d-4042-8e16-4faac62f72d3.png)
直接添加根目录，打开显示的是镜像的内容。 

请问怎么能添加物理机硬盘为驱动器呢？

**Comment by zhaojun1998** [comment]
这个问题是docker配置问题，请自行查阅docker文档及其相关资料。关键字为 docker路径映射



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月5日(周日) 晚上9:41
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] docker安装的如何配置物理机硬盘为驱动器？只能配置镜像内路径 (#269)




 

 添加物理机挂载的移动硬盘，就提示如图所示。
 

 直接添加根目录，打开显示的是镜像的内容。
 
请问怎么能添加物理机硬盘为驱动器呢？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DingChang90** [comment]
> 这个问题是docker配置问题，请自行查阅docker文档及其相关资料。关键字为 docker路径映射
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年9月5日(周日) 晚上9:41 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [zhaojun1998/zfile] docker安装的如何配置物理机硬盘为驱动器？只能配置镜像内路径 (#269) 添加物理机挂载的移动硬盘，就提示如图所示。 直接添加根目录，打开显示的是镜像的内容。 请问怎么能添加物理机硬盘为驱动器呢？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

谢谢大佬儿，已解决。

多增加一行
    -v /mnt/sda6:/mnt/sda6 \
就成功挂载了。
