### ISSUE TITLE
3.2 bug?

### ISSUE THREAD

**Issue by stilleshan** [zfile-dev/zfile#272]
docker 部署,从3.1升级到3.2 容器启动正常,但是打不开,显示502.

如果不挂载数据库,重新全新启动容器,install提交立刻刷新回install页面..

**Comment by zhaojun1998** [comment]
@stilleshan   

你更新太快了，哈哈哈，我刚调试好了，重新上传到了 CDN 和 DockerHub

不过你更新早的话，可能会碰上个 BUG，导致之前的 H2 数据库文件异常，只能删了重新初始化~~~

**Comment by stilleshan** [comment]
哈哈.留了一手备份了数据库...

那release页面的jar包就没法修改更新了吧?
只能用 https://c.jun6.net/ZFILE/zfile-release.war 了?

**Comment by zhaojun1998** [comment]
我都重新上传了，我的 CDN，Github Release，DockerHub 都更新了

**Comment by zhaojun1998** [comment]
验证没问题后，记得关闭 issue

**Comment by stilleshan** [comment]
测试 OK 了..

**Comment by zhaojun1998** [comment]
一样，release页的我也能换，已经换过了



---Original---
From: ***@***.***&gt;
Date: Sun, Sep 19, 2021 16:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [zhaojun1998/zfile] 3.2 bug? (#272)




 
哈哈.留了一手备份了数据库...
 
那release页面的jar包就没法修改更新了吧?
 只能用 https://c.jun6.net/ZFILE/zfile-release.war 了?
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
