### ISSUE TITLE
docker版无法安装

### ISSUE THREAD

**Issue by JohnsonRan** [zfile-dev/zfile#273]
docker部署后进入`域名/install`填好信息之后，点确认提示初始化成功但是却直接回到install界面，访问`域名/main`也回到install界面

**Comment by 97xiami** [comment]
刚刚测试过没有问题，install配置后自动跳至main

**Comment by zhaojun1998** [comment]
用哪个镜像安装的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月19日(周日) 晚上8:28
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [zhaojun1998/zfile] docker版无法安装 (#273)




 
刚刚测试过没有问题，install配置后自动跳至main
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JohnsonRan** [comment]
> 用哪个镜像安装的
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年9月19日(周日) 晚上8:28 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [zhaojun1998/zfile] docker版无法安装 (#273) 刚刚测试过没有问题，install配置后自动跳至main — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

zhaojun1998/zfile:latest

**Comment by JohnsonRan** [comment]
然后如果3.2用3.1的配置文件直接访问/main会报错

**Comment by zhaojun1998** [comment]
@JohnsonRan 停止删除容器，并删除镜像，重新下载试试，我重新 push 到 DokcerHub 上了

**Comment by JohnsonRan** [comment]
> @JohnsonRan 停止删除容器，并删除镜像，重新下载试试，我重新 push 到 DokcerHub 上了

现在能用了

**Comment by zhaojun1998** [comment]
好，那我关闭问题了
