### ISSUE TITLE
docker无法映射/root/zfile，会不停重启

### ISSUE THREAD

**Issue by 97xiami** [zfile-dev/zfile#274]
每次更新都要修改配置

**Comment by zhaojun1998** [comment]
什么意思，哪个配置文件



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月19日(周日) 晚上8:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] docker无法映射/root/zfile，会不停重启 (#274)




 
每次更新都要修改配置
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 97xiami** [comment]
端口，如果更新镜像就要重新修改，我想把zfile映射出来就不用更新后再修改了

**Comment by zhaojun1998** [comment]
这个后续会考虑放出来配置文件或者使用环境变量方式，不过这个版本改不了啦，

**Comment by 97xiami** [comment]
好的
