### ISSUE TITLE
前端分离部署在新版本去除 # 后无法通过 url 正确访问.

### ISSUE THREAD

**Issue by cxplay** [zfile-dev/zfile#275]
## 复现方法

将 3.2 版本前后端分离部署, 使用前端域名访问站点, 进入任意驱动器的目录使地址栏 url 跟随刷新, 复制此目录 url 后在新的窗口中粘贴并打开.

## 错误情况

可能是由于前端通过没有 # 的访问会被认为是静态资源下的目录而导致 404. 导致无法通过前端 url 进入目录, 以及管理后台.

如果去除 # 在新版本中前后端分离可能无法实现.

**Comment by zhaojun1998** [comment]
是的，新版本无法使用



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月20日(周一) 凌晨0:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] 前端分离部署在新版本去除 # 后无法通过 url 正确访问. (#275)




 
复现方法
 
将 3.2 版本前后端分离部署, 使用前端访问站点, 进入任意驱动器的目录使地址栏 url 跟随刷新, 复制此目录 url 后在新的窗口中粘贴并打开.
 
错误情况
 
可能是由于前端通过没有 # 的访问会被认为是静态资源下的目录而导致 404. 导致无法通过前端 url 进入目录, 以及管理后台.
 
因此在新版本中前后端分离可能无法实现.
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhaojun1998** [comment]
后续版本会增加配置文件，用户自由选择使用 history 路由还是 hash 路由。

**Comment by cxplay** [comment]
好的!
