### ISSUE TITLE
sharepoint无法获取令牌

### ISSUE THREAD

**Issue by xinghuan22** [zfile-dev/zfile#284]
## 我的环境

centos 7
## 错误日志

[zfile.log](https://github.com/zhaojun1998/zfile/files/7217001/zfile.log)
## 期望行为

点击获取sharepoint令牌，能够获取到令牌

## 当前行为
本人是免费申请的365教育版用户，持有sharepoint账号，但是无法获取令牌
![image](https://user-images.githubusercontent.com/66172622/134495800-0fe1b57e-5761-445d-b899-e7203ef6d21f.png)

**Comment by zhaojun1998** [comment]
可能你的教育版账户未开放api，或浏览器缓存导致获取失败。请先清理浏览器缓存再试。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月23日(周四) 晚上6:59
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] sharepoint无法获取令牌 (#284)




 
我的环境
 
centos 7
 
错误日志
 
zfile.log
 
期望行为
 
点击获取sharepoint令牌，能够获取到令牌
 
当前行为
 
本人是免费申请的365教育版用户，持有sharepoint账号，但是无法获取令牌
 
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xinghuan22** [comment]
请问如何开放api并查看站点名称，百度未果，特来询问




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhaojun1998/zfile"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月23日(星期四) 晚上7:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhaojun1998/zfile] sharepoint无法获取令牌 (#284)





 可能你的教育版账户未开放api，或浏览器缓存导致获取失败。请先清理浏览器缓存再试。 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2021年9月23日(周四) 晚上6:59 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;; 
 主题: [zhaojun1998/zfile] sharepoint无法获取令牌 (#284) 
 
 
 
 
   
 我的环境 
   
 centos 7 
   
 错误日志 
   
 zfile.log 
   
 期望行为 
   
 点击获取sharepoint令牌，能够获取到令牌 
   
 当前行为 
   
 本人是免费申请的365教育版用户，持有sharepoint账号，但是无法获取令牌 
   
   
 — 
 You are receiving this because you are subscribed to this thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhaojun1998** [comment]
你可以用其他程序，尝试是否可以正常绑定，如 Cloudreve，PyOne，PanIndex 等程序试试能否正常绑定。或者询问购买商是否开放了 api

**Comment by zhaojun1998** [comment]
长时间无回复，先关闭问题，有反馈再打开
