### ISSUE TITLE
前后分离部署模式下，无法进入后台或通过url访问目录

### ISSUE THREAD

**Issue by noisky** [zfile-dev/zfile#290]
前端地址：https://dl.ffis.me 部署在对象储存
后端地址：https://file.ffis.me
## 期望行为
1.前端可正常进入后台
https://dl.ffis.me/admin

2.前端可正常访问目录
https://dl.ffis.me/1/main/study/book

## 当前行为
以上两种访问方式均404，直接访问后端正常；
直接从首页访问目录正常，但是复制url地址后再次访问就会404

**Comment by zhaojun1998** [comment]
目前的history模式，（即去掉url中的#后）默认不支持前后端分离，需要后端支持。


或者如果对象存储支持的话。可以让404页面指向到index.html上。

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月8日(周五) 下午3:23
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] 前后分离部署模式下，无法进入后台或通过url访问目录 (#290)




 
前端地址：https://dl.ffis.me 部署在对象储存
 后端地址：https://file.ffis.me
 
期望行为
 
1.前端可正常进入后台
 https://dl.ffis.me/admin
 
2.前端可正常访问目录
 https://dl.ffis.me/1/main/study/book
 
当前行为
 
以上两种访问方式均404，直接访问后端正常；
 直接从首页访问目录正常，但是复制url地址后再次访问就会404
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by noisky** [comment]
新版本history模式默认是开启的，能手动关闭吗？
需要后端支持是指nginx配置支持还是代码层面支持？

**Comment by zhaojun1998** [comment]
目前是我在后端的Java代码中实现的。访问404的话。指向到index.html


3.2版本是默认开启的history模式。如使用hash模式。可自行重新编译前端代码。


后续版本会提供配置文件来控制路由模式



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月8日(周五) 下午4:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhaojun1998/zfile] 前后分离部署模式下，无法进入后台或通过url访问目录 (#290)




 
新版本history模式默认是开启的，能手动关闭吗？
 需要后端支持是指nginx配置支持还是代码层面支持？
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by noisky** [comment]
OK，我改成hash模式，前后分离恢复正常了，谢谢dalao
