### ISSUE TITLE
FTP存储策略

### ISSUE THREAD

**Issue by HoratioShaw** [zfile-dev/zfile#295]
使用最新版docker-zfile（3.2.0），看到issues里有人反馈并已在3.1版本解决，但是我使用FTP存储策略时仍然会出现“暂无数据”，用其他工具连接都是正常显示的，望修复！

**Comment by zhaojun1998** [comment]
在linux上，还是windows上搭建的zfile。ftp服务器呢。在哪搭建的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月21日(周四) 凌晨0:25
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] FTP存储策略 (Issue #295)




 
使用最新版docker-zfile（3.2.0），看到issues里有人反馈并已在3.1版本解决，但是我使用FTP存储策略时仍然会出现“暂无数据”，用其他工具连接都是正常显示的，望修复！
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HoratioShaw** [comment]
zfile和ftp都是linux

**Comment by hongzhongzhang** [comment]
3.2 版本，ftp和zfile同一台linux机器，直接部署的未使用docker，同样出现暂无数据
