### ISSUE TITLE
请问使用自己的Onedrive API时需要修改哪些部分？

### ISSUE THREAD

**Issue by xfrose** [zfile-dev/zfile#296]
大佬你好，我试着在azure申请了api，权限为
> 	Files.ReadWrite.All
	offline_access
	User.Read

替换了zfile/WEB-INF/classes/application.yaml里Onedrive部分的Client ID、密码及redirectUri，但是设置完成后打开主页，只显示了“文档、图片、OneDrive入门.pdf”，看不到其他任何文件和文件夹。
经过搜索，在[别人写的一篇教程](https://www.iwayen.cn/computer/25.html)里看到还需要在zfile/WEB-INF/classes/static/js/里把几个js文件的内容替换一下，但我在这个文件夹里找不到对应的可以替换的字段，请问是不是应该在别的地方替换一下？
谢谢！

**Comment by zhaojun1998** [comment]
只需要修改application.yml中的信息即可。
如之前添加的onedrive的驱动器，修改后要去后台重新获取access token 和refresh token。


只要重新获取后能获取到文件列表就是没问题的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月23日(周六) 凌晨3:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] 请问使用自己的Onedrive API时需要修改哪些部分？ (Issue #296)




 
大佬你好，我试着在azure申请了api，权限为
  
Files.ReadWrite.All
 offline_access
 User.Read
  
替换了zfile/WEB-INF/classes/application.yaml里Onedrive部分的Client ID、密码及redirectUri，但是设置完成后打开主页，只显示了“文档、图片、OneDrive入门.pdf”，看不到其他任何文件和文件夹。
 经过搜索，在别人写的一篇教程里看到还需要在zfile/WEB-INF/classes/static/js/里把几个js文件替换一下，但我在这个文件夹里找不到对应的可以替换的字段，请问是不是应该在别的地方替换一下？
 谢谢！
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhaojun1998** [comment]
长时间未回复，暂时关闭 issue，有问题请在打开。
