### ISSUE TITLE
支持文件搜索么？

### ISSUE THREAD

**Issue by ghost** [zfile-dev/zfile#301]
请问支持文件搜索么？

**Comment by zhaojun1998** [comment]
目前版本不支持

**Comment by ghost** [comment]
@zhaojun1998 有打算做吗？

**Comment by zhaojun1998** [comment]
目前所有存储源均未提供搜索api，故无法支持。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月9日(周二) 上午8:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhaojun1998/zfile] 支持文件搜索么？ (Issue #301)




 
@zhaojun1998 有打算做吗？
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ghost** [comment]
不能定时遍历存储库？

**Comment by zhaojun1998** [comment]
搜索一次就全部遍历一次么。


1.速度，平均调用一次api要0.2-0.5秒，按照最简单的100个文件夹，就需要20-50秒的时间才能出结果。这还是比较小的数据量。
2.成本，阿里云oss，腾讯云cos等对象存储类，都是会对api调用次数计费的。频繁调用可能会出较高的账单


3.经验，之前做过搜索，且是缓存了搜索结果，然后定期刷新缓存来实现的，结果弊大于利，除了上述两个问题，还有就是缓存的话，如果文件夹特别多，遇到过很多次，有用户缓存全部文件夹一个小时都没缓存完，但onedrive的下载链接有效期也仅有一个小时而已。基本导致不可用了。


还有就是缓存未全部完成时，让搜索的话，搜索到的可能不是全量内容，等全部遍历完再允许搜索的话，等待时间又太长。所以2.2版本后我屏蔽了搜索功能。


综上所述，在官方未提供搜索api的情况下，遍历实现搜索是一种非常不成熟且体验很差的方案



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月9日(周二) 上午9:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhaojun1998/zfile] 支持文件搜索么？ (Issue #301)




 
不能定时遍历存储库？
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ghost** [comment]
结果仅限本地吧，云盘就不做搜索功能了。

**Comment by zhaojun1998** [comment]
本地会支持的，遍历方式，搜索时间取决于磁盘速度

**Comment by ghost** [comment]
大概哪个版本上线？

个人认为搜索还是比较重要。至于云盘，想必应该比较少人使用吧？

**Comment by zhaojun1998** [comment]
大概 30% 使用本地，50% 使用 OneDrive 系列，剩下的使用 OSS, COS 等 S3 协议的云存储
