### ISSUE TITLE
feat:希望可以增加对阿里网盘的支持 

### ISSUE THREAD

**Issue by caiiicv** [zfile-dev/zfile#308]

**Comment by zhaojun1998** [comment]
阿里云未提供官方api，无法对接。自行抓取api，可能有封号风险，且对作者来说，有法律风险。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月7日(周二) 晚上9:27
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] feat:希望可以增加对阿里网盘的支持  (Issue #308)




 
概述
 
动机
 
详细解释
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by caiiicv** [comment]
非常遗憾！但可以理解，zfile做得非常棒希望作者可以继续维护下去。
