### ISSUE TITLE
添加onedrive显示报错

### ISSUE THREAD

**Issue by xuebiya** [zfile-dev/zfile#379]
## 我的环境
winserver2019
  请登录到管理后台，点击左侧系统监控, 复制或截图此页内容.
-->

## 错误日志
添加onedrive时候显示 Handler dispatch failed; nested exception is java.lang.IllegalAccessError: class im.zhaojun.zfile.common.util.ClassUtils (in unnamed module @0x6bf256fa) cannot access class sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl (in module java.base) because module java.base does not export sun.reflect.generics.reflectiveObjects to unnamed module @0x6bf256fa

[ZFile 诊断日志 - 2022-07-10 22_38_27.zip](https://github.com/zhaojun1998/zfile/files/9079263/ZFile.-.2022-07-10.22_38_27.zip)

## 当前行为

![1111111](https://user-images.githubusercontent.com/58581151/178149556-c6fcb41e-d686-4176-adf0-3cdf298ebb1a.png)

**Comment by zhaojun1998** [comment]
已沟通是 jdk 版本问题，应为 jdk8，实际为 jdk 18

**Comment by zhaojun1998** [comment]
Java版本用的哪个



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月10日(周日) 晚上10:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] 添加onedrive显示报错 (Issue #379)




 
我的环境
 
winserver2019
 请登录到管理后台，点击左侧系统监控, 复制或截图此页内容.
 --&gt;
 
错误日志
 
添加onedrive时候显示 Handler dispatch failed; nested exception is java.lang.IllegalAccessError: class im.zhaojun.zfile.common.util.ClassUtils (in unnamed module @0x6bf256fa) cannot access class sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl (in module java.base) because module java.base does not export sun.reflect.generics.reflectiveObjects to unnamed module @0x6bf256fa
 
ZFile 诊断日志 - 2022-07-10 22_38_27.zip
 
当前行为
